---
# tasks file for apigee-opdk-temporary-restore-targets/
- block:
  - name: Move to original location
    ignore_errors: yes
    shell: "mv {{ item.temporary_holding_folder }}/{{ item.file_name }} {{ item.original_folder }}/"
    with_items: "{{ temporary_move }}"

  - name: Remove temporary holding folder
    file:
      path: "{{ item.temporary_holding_folder }}"
      state: absent
    with_items: "{{ temporary_move }}"

  when: temporary_move is defined
